/*
    Exercise 2
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const normal = limit => {
    let total = 0;
    let a = 0;
    let b = 1;

    while(b < limit) {
        if(b % 2 === 0) total += b;

        // re-assign next values
        let c = a + b;
        a = b;
        b = c;
    }

    return total;
};

const recursive = (limit, a = 0, b = 1) => {
    // base
    if(b >= limit) return 0;

    // recursive: positive case
    if(b % 2 === 0) return b + recursive(limit, b, a + b);

    // recursive: negative case
    return recursive(limit, b, a + b);
};

const LIMIT = 4000000;
console.log('Normal:', normal(LIMIT));
console.log('Recursive:', recursive(LIMIT));